server:
  port: 8062

girl:
  name: Lily
  age: 18
  content: content:${name},age:${age}

spring:
  mvc:
    view:
      prefix: /
      suffix: .html
#  resources:
#    static-locations:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.happy.com:33060/daily?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: ang
    password: ang002

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      hbm2ddl:
       auto: update
    show-sql: true
